blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://djls.joshthomas.dev
    about: Check the documentation for configuration and troubleshooting guides.
  - name: Discussions
    url: https://github.com/joshuadavidthomas/django-language-server/discussions
    about: Ask questions and discuss ideas.
