[package]
name = "djls-dev"
version = "0.0.0"
edition = "2021"
publish = false

[[bin]]
name = "djls-dev"

[dependencies]
djls-semantic = { workspace = true }

anyhow = { workspace = true }
clap = { workspace = true }

[lints]
workspace = true
