[package]
name = "djls-semantic"
version = "0.0.0"
edition = "2021"

[dependencies]
djls-conf = { workspace = true }
djls-project = { workspace = true }
djls-python = { workspace = true }
djls-source = { workspace = true }
djls-templates = { workspace = true }
djls-workspace = { workspace = true }

camino = { workspace = true }
rustc-hash = { workspace = true }
salsa = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
ignore = { workspace = true }

[dev-dependencies]
djls-corpus = { workspace = true }
insta = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
