[package]
name = "djls-project"
version = "0.0.0"
edition = "2021"

[dependencies]
djls-conf = { workspace = true }
djls-python = { workspace = true }
djls-workspace = { workspace = true }

anyhow = { workspace = true }
camino = { workspace = true, features = ["serde1"] }
dotenvy = { workspace = true }
rustc-hash = { workspace = true }
ruff_python_parser = { workspace = true }
salsa = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
which = { workspace = true}

[build-dependencies]
which = { workspace = true }

[dev-dependencies]
djls-source = { workspace = true }

[lints]
workspace = true
